# Generated by Django 6.0.2 on 2026-03-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_contact_email_alter_task_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
