# Generated by Django 6.0.2 on 2026-03-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
