# Generated by Django 6.0.2 on 2026-03-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_deal_title_lead_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedBy',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assignedTo',
            new_name='assigned_to',
        ),
    ]
