# Generated by Django 6.0.2 on 2026-03-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_rename_assignedby_task_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
