# Generated by Django 6.0.2 on 2026-03-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
    ]
